services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
      - CUBEJS_DB_TYPE=duckdb
    volumes:
      - .:/cube/conf
      - ${HOME}/concept2/workouts:/data/workouts:ro